# Operation phase: train / eval / predict
phase: predict

classes: ['index', 'middle']

# Train / eval / predict paths
train_images_path: /home/andrew/projects/datasets/fingers/train/images
train_ann_path: /home/andrew/projects/datasets/fingers/train/xml
eval_images_path: "" 
eval_ann_path: ""
detect_images_path: /home/andrew/projects/datasets/fingers/quick_test/images
detect_output_path: /home/andrew/projects/htracking/tools/detect/output

# Model settings
model_params: 
    backbone_name: darknet_53
    backbone_pretrained: /home/andrew/projects/htracking/weights/darknet53_weights_pytorch.pth #  set empty to disable

# YOLO settings
yolo:
    anchors: [[[91,38], [100,204], [103,115]], 
              [[108,154], [117,219], [123,65]], 
              [[131,178], [137,112], [142,235]]]

# Optimization    
lr:
    backbone_lr: 0.001
    other_lr: 0.01
    freeze_backbone: False   #  freeze backbone wegiths to finetune
    decay_gamma: 0.1
    decay_step: 20           #  decay lr in every ? epochs
    
optimizer:
    type: sgd
    weight_decay: 0.00004 #4e-05, note that yaml doesn't support scientific notation

    
batch_size: 8  #16
epochs: 30    # Training epochs
image_h: 416 # Height
image_w: 416 # Width
gpu_devices: [3] #  [0, 1, 2]              
working_dir:  #  replace with your working dir
model_pretrained: /home/andrew/projects/htracking/tools/train/run/darknet_53/size416x416_try0/20180727112703/model.pth
evaluate_type": "" 
try: 0

confidence: 0.5 
confidence_thresh: 0.90
nms_thresh: 0.8

export_onnx: False


